Quantization and Binarization Implementations for Linear Layers
ReaLLMASIC/nanoGPT pull request #184
Opened 2024-06-10 19:17 UTC by mmoffatt2

Following code from [Quantization Repo](https://github.com/Alexstrasza98/Transformer-Quantization/blob/main/quantization/quantize.py), integrated quantization into the nanoGPT repo.

2024-06-10 20:18 UTC, gkielian commented
Awesome! This trains and converges!

We should try what the output from quantized inference looks like with the sample.py.
When trying to run sample.py on the created checkpoints, it encounters unexpected keys in the state_dict:
![image](https://github.com/ReaLLMASIC/nanoGPT/assets/10952473/d2f8179a-7153-470b-a422-e972aa748714)

Could you take a look into how to test with the sample.py (feel free to modify if needed)?

2024-06-17 18:57 UTC, gkielian requested changes
This is great, and looks like it can serve as the foundation for future quantization with  the other elements of the networks.

Please see comments in review and definitely reach out if there are questions on implementation of the remaining modifications.

2024-06-17 18:57 UTC, gkielian commented on gpt_conf.py
> +    quantize_attention: bool = True
In order to increase the combinations we can try, let's separate the different types of and levels of quantization.

Seeing the results from the llama.cpp and GGUF format communities, we'll probably be able to succeed with more aggressive quantization from the "Wk" and "Wq" matrices than "Wv" matrices. 

Keep one global quantization, maybe "quantize_attn_all", which if not None sets everything to one quantization, and otherwise would default to granular quantization settings:

quantize_attn_all = None
quantize_attn_q = None
quantize_attn_k = None
quantize_attn_v = None
quantize_attn_proj = None

Similarly for MLP:
quantize_mlp_all = None
quantize_mlp_up = None
quantize_mlp_down = None

2024-06-17 18:57 UTC, gkielian commented on gpt_conf.py
> +    quantization_choice: str = "none" # Choices: "none" "quantize" "binarize" "irbinarize"
Let's utilize the built-in None instead of string "none"

2024-06-17 18:57 UTC, gkielian commented on model.py
> +        if config.quantization_choice == 'quantize' and config.quantize_attention:
I see, adding the modifications here is a solid approach.

To prevent a long if else, utilize the linear_dictionary with the mappings (see end of variations/linear_variations)

We'll want to create polymorphism between the different alternatives, so use
Quantized_Linear( config.n_embd, config.n_embd, config=config) as the function signatures, using the config parameter in the  __init__ of each to set the self.bias and self.quantization_bits for each class (if needed).

Handle 
1. Polymorphism amongst the

2024-06-17 18:57 UTC, gkielian commented on model.py
> +
Great, and reduce the size using dictionary and polymorphism

2024-06-17 18:57 UTC, gkielian commented on model.py
> +            self.linear_variant = QuantizedLinear
After adding to the linear_dictionary can save these four lines.

2024-06-17 18:57 UTC, gkielian commented on model.py
> +                self.c_proj = self.linear_variant(4 * config.n_embd, config.n_embd, bias=config.bias)
Use  polymorphism and linear_dictionary for this section also

2024-06-17 18:57 UTC, gkielian commented on quantization/quantize.py
Keep the common quantization features in this file, and move the Linear variations to the variations/linear_variations folder.

Then add this file as an import to the linear_variations.py,so that we can reuse this code as a basis for future quantization of activation functions, normalization operations, and softmax alternatives

2024-06-17 18:57 UTC, gkielian commented on sample.py
Excellent! what would be a good sample command for running this be? Would you be able to add a section in the README.md with a few lines for demonstration (python3 data/shakespeare_char/prepare.py; python3  train.py; python3 sample.py --argparse args)  with an image sample output?

2024-06-28 01:28 UTC, mmoffatt2 commented
Unfortunately, I didn't think ahead to split these changes into multiple PRs. I will try to summarize all the changes as best as possible.

Updates:
Added two options for quantization: "affine_quant" and "stochastic_quant"
Added QuantizedEmbedding to position_encoding_variations.py, which can be used for word embeddings and position embeddings
Added quantize_helper function which is used for quantization of the outputs of matrix multiplications and linear layers

train.py arguments:
"quantization_linear_method": quantization method used for all quantized linear layers
"quantize_wte": whether the word embedding weights are quantized (using QuantizedEmbedding)
"quantize_wpe": whether the position embedding weights are quantized (using QuantizedEmbedding)
"quantization_embedding_method": method of quantization used for embeddings
"quantize_attn_all": this boolean argument will quantize everything in the attn layer, including outputs and linear layers
"quantize_c_attn_q": whether the query weights are quantized (using QuantizedLinear)
"quantize_c_attn_k": whether the key weights are quantized (using QuantizedLinear)
"quantize_c_attn_v": whether the value weights are quantized (using QuantizedLinear)
"quantize_q": whether the query output is quantized (using quantize_helper)
"quantize_k": whether the key output is quantized (using quantize_helper)
"quantize_v": whether the value output is quantized (using quantize_helper)
"quantize_q_k_mult": whether the output of the query key matrix multiplication is quantized (using quantize_helper)
"quantize_softmax_v_mult": whether the output of the softmax value matrix multiplication is quantized (using quantize_helper)
"quantize_softmax": whether the output of the softmax variant is quantized (using quantize_helper)
"quantize_attn_proj": whether the output projection is quantized (using QuantizedLinear)
"quantize_mlp_all": this boolean argument will quantize everything in the mlp layer, including activation outputs and linear layers
"quantize_mlp_up": whether the mlp_up weights are quantized (using QuantizedLinear)
"quantize_mlp_down": whether the mlp_down weights are quantized (using QuantizedLinear)
"quantize_activation": whether the output of the activation function is quantized (using quantize_helper)
"quantization_activation_method": method of quantization for the activation output

Example code for running train.py:
python3 train.py --device="cuda" --dataset="shakespeare_char" --out_dir="out_shakespeare_char" --linear_variant="quantized_linear" --quantize_attn_all --quantize_mlp_all --quantize_wte --quantize_wpe

Example code for running sample.py:
python3 sample.py --out_dir="out_shakespeare_char" --device="cuda" --quant_weights_file="shakespeare" --visualize_weights_dir="shakespeare_weights"

2024-07-11 23:48 UTC, gkielian commented
Will start diving into the code. one thing we'll have to separate out the quantization for the attention output projection -- experiment with this show that it might need it's own unique precision (possibly higher) in order to operate well.

2024-08-15 19:24 UTC, closed without merging