QuantizedEmbedding
ReaLLMASIC/nanoGPT pull request #210
Opened 2024-07-31 06:49 UTC by mmoffatt2

Moved quantize embedding code from "Quantization and Binarization Implementations for Linear Layers" to new PR

2024-08-01 19:28 UTC, gkielian commented on quantization/quantize.py
> +_fake_quantize = FakeLinearQuantizationFunction.apply
Maybe remove from this CL

2024-08-01 19:31 UTC, gkielian commented on model.py
> +            if self.config.quantize_wpe:
maybe add `and if self.config.use_abs_pos_embeddings`

2024-08-01 19:31 UTC, gkielian commented on model.py
> +            if self.config.quantize_wpe:
There might be some others as well

2024-08-01 19:33 UTC, gkielian commented on train.py
> +    model_group.add_argument("--quantize_wpe", default=None, action=argparse.BooleanOptionalAction, help="Whether the word position embedding is quantized")
If you can add wte quantization precision and also one for wpe

2024-08-01 19:37 UTC, gkielian requested changes
Looks good! Added feedback within single comments

2024-08-02 00:20 UTC, mmoffatt2 commented
Addressed PR feedback. With wte and wpe quantized, model still converges and has good inference sample output.

![image](https://github.com/user-attachments/assets/2aae5a2a-1da2-4bc3-8417-2de3250d4bfc)
![image](https://github.com/user-attachments/assets/fd75ce14-3959-401b-af9c-497fd625ba93)

2024-08-06 03:24 UTC, gkielian approved these changes

2024-08-06 03:29 UTC, gkielian commented
Looks good! : D 

model.py One step closer to having full quantization.

Merging.

2024-08-06 03:29 UTC, merged