Quantized Linear
ReaLLMASIC/nanoGPT pull request #214
Opened 2024-08-01 18:38 UTC by mmoffatt2

Moved quantize lineaer code from "Quantization and Binarization Implementations for Linear Layers" to new PR

2024-08-01 19:43 UTC, djlisbonne commented
Does this also add QAT / is there a cmd line flag for that?

2024-08-01 19:46 UTC, gkielian requested changes
Let's think about ways to prevent the if else statements, must be something we can do.

2024-08-01 19:46 UTC, gkielian commented on gpt_conf.py
> +    quantization_linear_bits: int = 8
It will be a lot more lines, but let's add ability to quantize the outputs of each of the linear matrices separately.

2024-08-01 19:46 UTC, gkielian commented on model.py
> +
Let's think how we can reduce the if thens here, maybe some strategy with a dictionary, or an additional boolean flag for uniform attn precision

2024-08-01 19:46 UTC, gkielian commented on model.py
> +                self.c_proj = linear_dictionary[config.linear_variant_mlp](4 * config.n_embd, config.n_embd, config=config, bias=config.bias)
Same, hoping we can reduce the if elses

2024-08-01 19:46 UTC, gkielian commented on model.py
> +                self.c_fc_out = linear_dictionary[config.linear_variant_mlp](4 * config.n_embd, config.n_embd, config=config)
Same

2024-08-01 19:46 UTC, gkielian commented on train.py
> +        "--linear_variant_attn",
I think this intersects another PR, I'll get back to you on this one.

2024-08-01 19:46 UTC, gkielian commented on variations/linear_variations.py
> +        self.warmup_step = warmup_step
There should be a config for this -- in fact is this tied to warmup iterations?

2024-08-01 19:46 UTC, gkielian commented on variations/linear_variations.py
> +    def __init__(self, in_features, out_features, config, bias=True, warmup_step=0):
Should we tie the warmup_step to warmup_iters?

2024-08-02 16:27 UTC, mmoffatt2 commented
> Does this also add QAT / is there a cmd line flag for that?

Currently, this PR only supports QAT

2024-08-02 20:36 UTC, mmoffatt2 commented on train.py
> +        "--linear_variant_attn",
I saw this was in the "Add granular rmsnorm linear settings so that we can and bitlinear with RMSNorm" PR, so I copied the same format.

2024-08-02 20:36 UTC, mmoffatt2 commented on variations/linear_variations.py
> +        self.warmup_step = warmup_step
Not sure if we want to directly tie this to warmup_iters. For now, I added a quantization_warmup_iters config argument.

2024-08-08 05:56 UTC, gkielian requested changes
Have a few ideas how to further min the code.

Going to start working through the quantization section tomorrow

2024-08-08 05:56 UTC, gkielian commented on train.py
> +            "quantized_linear"
Since these are shared, we can create a linear_variant list and use for each of the linear variant argparses

2024-08-08 05:56 UTC, gkielian commented on train.py
> +    model_group.add_argument("--quantize_wte_method", type=str, default="affine_quant", choices=["symmetric_quant", "affine_quant", "stochastic_quant"], help="function used for word embedding quantiz
Same here, we can create a choice list for each of these, to help prevent massive updates.

2024-08-09 19:23 UTC, gkielian approved these changes

2024-08-09 19:23 UTC, merged