Add Randomness Seed Parameter
ReaLLMASIC/nanoGPT pull request #68
Opened 2024-01-24 22:21 UTC by mmoffatt2

PR 1:
-Add the '--seed' argparse parameter to train.py and verify using config.json and run_experiments.py script

2024-01-25 21:23 UTC, gkielian commented on explorations/config.json
> +    "seed":  ["1337"]
Looks good,

Please move swap the seed line with the tensorboard run name line

-Also add a 4-5 more additional seed values for testing -- make sure to also include "9001"  : )

2024-01-25 21:47 UTC, gkielian requested changes
Sorry forgot to specify for PR#1 to create a new config.json fie -- maybe called something like `random_seed_tests.json`

This will be important for PR#3.

2024-01-26 21:10 UTC, gkielian commented
Looks good, am using this right now on to test out stability, ping me after making the adjustments to the json file as noted above, and looks good to merge.

Direct link to json discussion:
https://github.com/ReaLLMASIC/nanoGPT/pull/68/files/0c2f96cc421c370f489d270ca3c676a015377398#diff-918e2e08a60b7089115fbd3995a1e61c028a39617f5aff63ad36098b59d93a5a

2024-01-26 21:17 UTC, mmoffatt2 commented
> Sorry forgot to specify for PR#1 to create a new config.json fie -- maybe called something like `random_seed_tests.json`
> 
> This will be important for PR#3.

2024-01-26 21:45 UTC, gkielian approved these changes

2024-01-26 21:45 UTC, gkielian commented on explorations/random_seed_tests.json
> +
Latest looks really good, we'll have to remove the constantmax_base and other block sizes for now,

Also note that we don't have to use the {} method for setting options for the softmax_variant_attn, since the conditions are blank.

Good stuff, I made very slight code adjustments, please see the following: 
```json
[
  {
    "max_iters": ["3000"],
    "n_layer": ["6"],
    "n_head": ["6"],
    "n_embd": ["384"],
    "block_size":["256"],
    "use_post_ln": [true],
    "device": ["cuda"],
    "dtype": ["float16"],
    "dataset": ["shakespeare_char"],
    "use_rotary_embeddings": [false],
    "use_abs_pos_embeddings": [true],
    "seed":  [
      "1197", "1276", "1789", "1835", "2627", "2739", "2788", "3393", "3618",
      "4042", "4691", "4963", "5021", "5772", "6337", "7748", "8423", "9001",
      "9448", "9473"
    ],
    "softmax_variant_attn": ["softermax", "softmax", "constantmax"],
    "tensorboard_run_name": ["random_seed_tests"]
  }
]

```

2024-01-26 21:45 UTC, gkielian commented on train.py
> +    training_group.add_argument("--seed", default=1337, type=int)
excellent

2024-01-26 21:45 UTC, gkielian commented on train.py
> +        torch.manual_seed(self.args.seed + self.seed_offset)
looks good

2024-01-26 21:46 UTC, gkielian approved these changes

2024-01-26 21:56 UTC, merged